--------------------------------------------------------
-- Archivo creado  - domingo-mayo-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEC_DIA_SEMANA
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_DIA_SEMANA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_HABITACION
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_HABITACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_MONEDA
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_MONEDA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ORDEN_PEDIDO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_ORDEN_PEDIDO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ORDEN_PEDIDO_DET
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_ORDEN_PEDIDO_DET"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_PERSONA
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_PERSONA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_PLATO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_PLATO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_PRODUCTO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_PRODUCTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_PROVEEDOR
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_PROVEEDOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_RESERVA
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_RESERVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_RESERVA_DETALLE
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_RESERVA_DETALLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ROL_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_ROL_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_RUBRO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_RUBRO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_SERVICIO_COMEDOR
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_SERVICIO_COMEDOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_STATUS_HABITACION
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_STATUS_HABITACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_TIPO_CAMBIO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_TIPO_CAMBIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_TIPO_CAMBIO_VALOR
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_TIPO_CAMBIO_VALOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_TIPO_HABITACION
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_TIPO_HABITACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_TIPO_PERSONA
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_TIPO_PERSONA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_TIPO_PRODUCTO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_TIPO_PRODUCTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTALCLARITA"."SEC_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DIA_SEMANA
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."DIA_SEMANA" 
   (	"ID_DIA_SEMANA" NUMBER(10,0), 
	"DSC_DIA_SEMANA" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table HABITACION
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."HABITACION" 
   (	"ID_HABITACION" NUMBER(10,0), 
	"PRECIO" NUMBER(18,4), 
	"DISPONIBILIDAD" CHAR(1 CHAR), 
	"ID_TIPO_HABITACION" NUMBER(10,0), 
	"ID_STATUS_HABITACION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table MINUTA
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."MINUTA" 
   (	"ID_PLATO" NUMBER(10,0), 
	"ID_SERVICIO_COMEDOR" NUMBER(10,0), 
	"ID_DIA_SEMANA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table MONEDA
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."MONEDA" 
   (	"ID_MONEDA" NUMBER(10,0), 
	"DSC_MONEDA" VARCHAR2(20 CHAR), 
	"COD_MONEDA" CHAR(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table ORDEN_PEDIDO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."ORDEN_PEDIDO" 
   (	"ID_ORDEN_PEDIDO" NUMBER(10,0), 
	"ID_PROVEEDOR" NUMBER(10,0), 
	"FECHA_SOLICITUD" DATE, 
	"FECHA_RECEPCION" DATE, 
	"ID_USUARIO_CREA_OP" NUMBER(10,0), 
	"OBSERVACIONES" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table ORDEN_PEDIDO_DET
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."ORDEN_PEDIDO_DET" 
   (	"ID_ORDEN_PEDIDO_DET" NUMBER(10,0), 
	"ID_ORDEN_PEDIDO" NUMBER(10,0), 
	"SEC_ORDEN_PEDIDO_DET" NUMBER(3,0), 
	"ID_PRODUCTO" NUMBER(10,0), 
	"CANTIDAD" NUMBER(10,0), 
	"PRECIO_UNITARIO" NUMBER(18,4), 
	"MONTO_TOTAL_OP" NUMBER(18,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."PERSONA" 
   (	"ID_PERSONA" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"AP_PATERNO" VARCHAR2(50 CHAR), 
	"AP_MATERNO" VARCHAR2(50 CHAR), 
	"RUT" VARCHAR2(8 CHAR), 
	"DV" CHAR(1 CHAR), 
	"FECHA_NACIMIENTO" DATE, 
	"EDAD" NUMBER(3,0), 
	"SEXO" CHAR(1 CHAR), 
	"EMAIL" VARCHAR2(60 CHAR), 
	"TELEFONO" VARCHAR2(20 CHAR), 
	"ID_TIPO_PERSONA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table PLATO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."PLATO" 
   (	"ID_PLATO" NUMBER(10,0), 
	"DSC_PLATO" VARCHAR2(50 CHAR), 
	"PRECIO" NUMBER(18,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(10,0), 
	"DSC_PRODUCTO" VARCHAR2(100 CHAR), 
	"ID_TIPO_PRODUCTO" NUMBER(10,0), 
	"ID_PROVEEDOR" NUMBER(10,0), 
	"FECHA_VENCIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(10,0), 
	"ID_PERSONA" NUMBER(10,0), 
	"ID_RUBRO" NUMBER(10,0), 
	"NOMBRE_CONTACTO" VARCHAR2(100 CHAR), 
	"TELEFONO_CONTACTO" VARCHAR2(20 CHAR), 
	"EMAIL_CONTACTO" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."RESERVA" 
   (	"ID_RESERVA" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"FECHA_CHECKIN" DATE, 
	"FECHA_CHECKOUT" DATE, 
	"CANT_HUESPEDES" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table RESERVA_DETALLE
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."RESERVA_DETALLE" 
   (	"ID_RESERVA_DETALLE" NUMBER(10,0), 
	"ID_RESERVA" NUMBER(10,0), 
	"ID_HABITACION" NUMBER(10,0), 
	"ID_PERSONA" NUMBER(10,0), 
	"CONFIRMA_RESERVA" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table ROL_USUARIO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."ROL_USUARIO" 
   (	"ID_ROL_USUARIO" NUMBER(10,0), 
	"ROL_USUARIO" VARCHAR2(50 CHAR), 
	"DESCRIPCION" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table RUBRO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."RUBRO" 
   (	"ID_RUBRO" NUMBER(10,0), 
	"DSC_RUBRO" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table SERVICIO_COMEDOR
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."SERVICIO_COMEDOR" 
   (	"ID_SERVICIO_COMEDOR" NUMBER(10,0), 
	"DSC_SERVICIO_COMEDOR" VARCHAR2(50 BYTE), 
	"EST_SERVICIO_COMEDOR" CHAR(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table STATUS_HABITACION
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."STATUS_HABITACION" 
   (	"ID_STATUS_HABITACION" NUMBER(10,0), 
	"COD_STATUS_HABITACION" CHAR(4 CHAR), 
	"DSC_STATUS_HABITACION" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table TIPO_CAMBIO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."TIPO_CAMBIO" 
   (	"ID_TIPO_CAMBIO" NUMBER(10,0), 
	"ID_MONEDA_ORIGEN" NUMBER(10,0), 
	"DSC_MONEDA_ORIGEN" CHAR(3 CHAR), 
	"ID_MONEDA_DESTINO" NUMBER(10,0), 
	"DSC_MONEDA_DESTINO" CHAR(3 CHAR), 
	"DSC_TIPO_CAMBIO" VARCHAR2(30 CHAR), 
	"EST_TIPO_CAMBIO" CHAR(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table TIPO_CAMBIO_VALOR
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."TIPO_CAMBIO_VALOR" 
   (	"ID_TIPO_CAMBIO_VALOR" NUMBER(10,0), 
	"ID_TIPO_CAMBIO" NUMBER(10,0), 
	"FECHA" DATE, 
	"VALOR_TIPO_CAMBIO" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table TIPO_HABITACION
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."TIPO_HABITACION" 
   (	"ID_TIPO_HABITACION" NUMBER(10,0), 
	"DSC_TIPO_HABITACION" VARCHAR2(50 CHAR), 
	"COD_TIPO_HABITACION" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table TIPO_PERSONA
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."TIPO_PERSONA" 
   (	"ID_TIPO_PERSONA" NUMBER(10,0), 
	"DSC_TIPO_PERSONA" VARCHAR2(50 CHAR), 
	"ABR_TIPO_PERSONA" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table TIPO_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."TIPO_PRODUCTO" 
   (	"ID_TIPO_PRODUCTO" NUMBER(10,0), 
	"DSC_TIPO_PRODUCTO" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "HOSTALCLARITA"."USUARIO" 
   (	"ID_USUARIO" NUMBER(10,0), 
	"ID_PERSONA" NUMBER(10,0), 
	"USER_NAME" VARCHAR2(30 CHAR), 
	"USER_PASS" VARCHAR2(500 CHAR), 
	"ID_ROL_USUARIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
REM INSERTING into HOSTALCLARITA.DIA_SEMANA
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.HABITACION
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.MINUTA
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.MONEDA
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.ORDEN_PEDIDO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.ORDEN_PEDIDO_DET
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.PERSONA
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.PLATO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.PRODUCTO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.PROVEEDOR
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.RESERVA
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.RESERVA_DETALLE
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.ROL_USUARIO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.RUBRO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.SERVICIO_COMEDOR
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.STATUS_HABITACION
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.TIPO_CAMBIO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.TIPO_CAMBIO_VALOR
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.TIPO_HABITACION
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.TIPO_PERSONA
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.TIPO_PRODUCTO
SET DEFINE OFF;
REM INSERTING into HOSTALCLARITA.USUARIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index HABITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."HABITACION_PK" ON "HOSTALCLARITA"."HABITACION" ("ID_HABITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index RESERVA_DETALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."RESERVA_DETALLE_PK" ON "HOSTALCLARITA"."RESERVA_DETALLE" ("ID_RESERVA_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index TIPO_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."TIPO_PRODUCTO_PK" ON "HOSTALCLARITA"."TIPO_PRODUCTO" ("ID_TIPO_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index RUBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."RUBRO_PK" ON "HOSTALCLARITA"."RUBRO" ("ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index STATUS_HABITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."STATUS_HABITACION_PK" ON "HOSTALCLARITA"."STATUS_HABITACION" ("ID_STATUS_HABITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."PRODUCTO_PK" ON "HOSTALCLARITA"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."PERSONA_PK" ON "HOSTALCLARITA"."PERSONA" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index MINUTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."MINUTA_PK" ON "HOSTALCLARITA"."MINUTA" ("ID_PLATO", "ID_SERVICIO_COMEDOR", "ID_DIA_SEMANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index RESERVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."RESERVA_PK" ON "HOSTALCLARITA"."RESERVA" ("ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."PROVEEDOR_PK" ON "HOSTALCLARITA"."PROVEEDOR" ("ID_PROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index DIA_SEMANA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."DIA_SEMANA_PK" ON "HOSTALCLARITA"."DIA_SEMANA" ("ID_DIA_SEMANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index PLATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."PLATO_PK" ON "HOSTALCLARITA"."PLATO" ("ID_PLATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index TIPO_CAMBIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."TIPO_CAMBIO_PK" ON "HOSTALCLARITA"."TIPO_CAMBIO" ("ID_TIPO_CAMBIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index ORDEN_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."ORDEN_PEDIDO_PK" ON "HOSTALCLARITA"."ORDEN_PEDIDO" ("ID_ORDEN_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index TIPO_CAMBIO_VALOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."TIPO_CAMBIO_VALOR_PK" ON "HOSTALCLARITA"."TIPO_CAMBIO_VALOR" ("ID_TIPO_CAMBIO_VALOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index SERVICIO_COMEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."SERVICIO_COMEDOR_PK" ON "HOSTALCLARITA"."SERVICIO_COMEDOR" ("ID_SERVICIO_COMEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index TIPO_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."TIPO_PERSONA_PK" ON "HOSTALCLARITA"."TIPO_PERSONA" ("ID_TIPO_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index MONEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."MONEDA_PK" ON "HOSTALCLARITA"."MONEDA" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."USUARIO_PK" ON "HOSTALCLARITA"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index ORDEN_PEDIDO_DET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."ORDEN_PEDIDO_DET_PK" ON "HOSTALCLARITA"."ORDEN_PEDIDO_DET" ("ID_ORDEN_PEDIDO_DET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index TIPO_HABITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."TIPO_HABITACION_PK" ON "HOSTALCLARITA"."TIPO_HABITACION" ("ID_TIPO_HABITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Index ROL_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTALCLARITA"."ROL_USUARIO_PK" ON "HOSTALCLARITA"."ROL_USUARIO" ("ID_ROL_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO" ;
--------------------------------------------------------
--  DDL for Trigger TRG_DIA_SEMANAID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_DIA_SEMANAID" BEFORE
    INSERT ON DIA_SEMANA
    FOR EACH ROW
     WHEN ( new.ID_DIA_SEMANA IS NULL ) BEGIN
    :new.ID_DIA_SEMANA := SEC_DIA_SEMANA.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_DIA_SEMANAID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_HABITACIONID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_HABITACIONID" BEFORE
    INSERT ON HABITACION
    FOR EACH ROW
     WHEN ( new.ID_HABITACION IS NULL ) BEGIN
    :new.ID_HABITACION := SEC_HABITACION.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_HABITACIONID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MONEDAID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_MONEDAID" BEFORE
    INSERT ON MONEDA
    FOR EACH ROW
     WHEN ( new.ID_MONEDA IS NULL ) BEGIN
    :new.ID_MONEDA := SEC_MONEDA.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_MONEDAID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDEN_PEDIDO_DETID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_ORDEN_PEDIDO_DETID" BEFORE
    INSERT ON ORDEN_PEDIDO_DET
    FOR EACH ROW
     WHEN ( new.ID_ORDEN_PEDIDO_DET IS NULL ) BEGIN
    :new.ID_ORDEN_PEDIDO_DET := SEC_ORDEN_PEDIDO_DET.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_ORDEN_PEDIDO_DETID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDEN_PEDIDOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_ORDEN_PEDIDOID" BEFORE
    INSERT ON ORDEN_PEDIDO
    FOR EACH ROW
     WHEN ( new.ID_ORDEN_PEDIDO IS NULL ) BEGIN
    :new.ID_ORDEN_PEDIDO := SEC_ORDEN_PEDIDO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_ORDEN_PEDIDOID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PERSONAID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_PERSONAID" BEFORE
    INSERT ON PERSONA
    FOR EACH ROW
     WHEN ( new.ID_PERSONA IS NULL ) BEGIN
    :new.ID_PERSONA := SEC_PERSONA.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_PERSONAID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PLATOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_PLATOID" BEFORE
    INSERT ON PLATO
    FOR EACH ROW
     WHEN ( new.ID_PLATO IS NULL ) BEGIN
    :new.ID_PLATO := SEC_PLATO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_PLATOID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCTOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_PRODUCTOID" BEFORE
    INSERT ON PRODUCTO
    FOR EACH ROW
     WHEN ( new.ID_PRODUCTO IS NULL ) BEGIN
    :new.ID_PRODUCTO := SEC_PRODUCTO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_PRODUCTOID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PROVEEDORID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_PROVEEDORID" BEFORE
    INSERT ON PROVEEDOR
    FOR EACH ROW
     WHEN ( new.ID_PROVEEDOR IS NULL ) BEGIN
    :new.ID_PROVEEDOR := SEC_PROVEEDOR.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_PROVEEDORID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RESERVA_DETALLEID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_RESERVA_DETALLEID" BEFORE
    INSERT ON RESERVA_DETALLE
    FOR EACH ROW
     WHEN ( new.ID_RESERVA_DETALLE IS NULL ) BEGIN
    :new.ID_RESERVA_DETALLE := SEC_RESERVA_DETALLE.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_RESERVA_DETALLEID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RESERVAID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_RESERVAID" BEFORE
    INSERT ON RESERVA
    FOR EACH ROW
     WHEN ( new.ID_RESERVA IS NULL ) BEGIN
    :new.ID_RESERVA := SEC_RESERVA.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_RESERVAID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ROL_USUARIOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_ROL_USUARIOID" BEFORE
    INSERT ON ROL_USUARIO
    FOR EACH ROW
     WHEN ( new.ID_ROL_USUARIO IS NULL ) BEGIN
    :new.ID_ROL_USUARIO := SEC_ROL_USUARIO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_ROL_USUARIOID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RUBROID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_RUBROID" BEFORE
    INSERT ON RUBRO
    FOR EACH ROW
     WHEN ( new.ID_RUBRO IS NULL ) BEGIN
    :new.ID_RUBRO := SEC_RUBRO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_RUBROID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SERVICIO_COMEDORID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_SERVICIO_COMEDORID" BEFORE
    INSERT ON SERVICIO_COMEDOR
    FOR EACH ROW
     WHEN ( new.ID_SERVICIO_COMEDOR IS NULL ) BEGIN
    :new.ID_SERVICIO_COMEDOR := SEC_SERVICIO_COMEDOR.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_SERVICIO_COMEDORID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STATUS_HABITACIONID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_STATUS_HABITACIONID" BEFORE
    INSERT ON STATUS_HABITACION
    FOR EACH ROW
     WHEN ( new.ID_STATUS_HABITACION IS NULL ) BEGIN
    :new.ID_STATUS_HABITACION := SEC_STATUS_HABITACION.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_STATUS_HABITACIONID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TIPO_CAMBIOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_TIPO_CAMBIOID" BEFORE
    INSERT ON TIPO_CAMBIO
    FOR EACH ROW
     WHEN ( new.ID_TIPO_CAMBIO IS NULL ) BEGIN
    :new.ID_TIPO_CAMBIO := SEC_TIPO_CAMBIO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_TIPO_CAMBIOID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TIPO_CAMBIO_VALORID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_TIPO_CAMBIO_VALORID" BEFORE
    INSERT ON TIPO_CAMBIO_VALOR
    FOR EACH ROW
     WHEN ( new.ID_TIPO_CAMBIO_VALOR IS NULL ) BEGIN
    :new.ID_TIPO_CAMBIO_VALOR := SEC_TIPO_CAMBIO_VALOR.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_TIPO_CAMBIO_VALORID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TIPO_HABITACIONID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_TIPO_HABITACIONID" BEFORE
    INSERT ON TIPO_HABITACION
    FOR EACH ROW
     WHEN ( new.ID_TIPO_HABITACION IS NULL ) BEGIN
    :new.ID_TIPO_HABITACION := SEC_TIPO_HABITACION.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_TIPO_HABITACIONID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TIPO_PERSONAID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_TIPO_PERSONAID" BEFORE
    INSERT ON TIPO_PERSONA
    FOR EACH ROW
     WHEN ( new.ID_TIPO_PERSONA IS NULL ) BEGIN
    :new.ID_TIPO_PERSONA := SEC_TIPO_PERSONA.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_TIPO_PERSONAID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TIPO_PRODUCTOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_TIPO_PRODUCTOID" BEFORE
    INSERT ON TIPO_PRODUCTO
    FOR EACH ROW
     WHEN ( new.ID_TIPO_PRODUCTO IS NULL ) BEGIN
    :new.ID_TIPO_PRODUCTO := SEC_TIPO_PRODUCTO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_TIPO_PRODUCTOID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USUARIOID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTALCLARITA"."TRG_USUARIOID" BEFORE
    INSERT ON USUARIO
    FOR EACH ROW
     WHEN ( new.ID_USUARIO IS NULL ) BEGIN
    :new.ID_USUARIO := SEC_USUARIO.nextval;
END;
/
ALTER TRIGGER "HOSTALCLARITA"."TRG_USUARIOID" ENABLE;
--------------------------------------------------------
--  Constraints for Table DIA_SEMANA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."DIA_SEMANA" ADD CONSTRAINT "DIA_SEMANA_PK" PRIMARY KEY ("ID_DIA_SEMANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."DIA_SEMANA" MODIFY ("ID_DIA_SEMANA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_HABITACION
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_HABITACION" ADD CONSTRAINT "TIPO_HABITACION_PK" PRIMARY KEY ("ID_TIPO_HABITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."TIPO_HABITACION" MODIFY ("ID_TIPO_HABITACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MINUTA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."MINUTA" ADD CONSTRAINT "MINUTA_PK" PRIMARY KEY ("ID_PLATO", "ID_SERVICIO_COMEDOR", "ID_DIA_SEMANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."MINUTA" MODIFY ("ID_DIA_SEMANA" NOT NULL ENABLE);
  ALTER TABLE "HOSTALCLARITA"."MINUTA" MODIFY ("ID_SERVICIO_COMEDOR" NOT NULL ENABLE);
  ALTER TABLE "HOSTALCLARITA"."MINUTA" MODIFY ("ID_PLATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_CAMBIO_VALOR
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO_VALOR" ADD CONSTRAINT "TIPO_CAMBIO_VALOR_PK" PRIMARY KEY ("ID_TIPO_CAMBIO_VALOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO_VALOR" MODIFY ("ID_TIPO_CAMBIO_VALOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."RESERVA" ADD CONSTRAINT "RESERVA_PK" PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."RESERVA" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICIO_COMEDOR
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."SERVICIO_COMEDOR" ADD CONSTRAINT "SERVICIO_COMEDOR_PK" PRIMARY KEY ("ID_SERVICIO_COMEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."SERVICIO_COMEDOR" MODIFY ("ID_SERVICIO_COMEDOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."PROVEEDOR" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "HOSTALCLARITA"."PROVEEDOR" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "HOSTALCLARITA"."PROVEEDOR" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PLATO" ADD CONSTRAINT "PLATO_PK" PRIMARY KEY ("ID_PLATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."PLATO" MODIFY ("ID_PLATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PERSONA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_PERSONA" ADD CONSTRAINT "TIPO_PERSONA_PK" PRIMARY KEY ("ID_TIPO_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."TIPO_PERSONA" MODIFY ("ID_TIPO_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVA_DETALLE
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."RESERVA_DETALLE" ADD CONSTRAINT "RESERVA_DETALLE_PK" PRIMARY KEY ("ID_RESERVA_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."RESERVA_DETALLE" MODIFY ("ID_RESERVA_DETALLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN_PEDIDO_DET
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO_DET" ADD CONSTRAINT "ORDEN_PEDIDO_DET_PK" PRIMARY KEY ("ID_ORDEN_PEDIDO_DET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO_DET" MODIFY ("ID_ORDEN_PEDIDO_DET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS_HABITACION
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."STATUS_HABITACION" ADD CONSTRAINT "STATUS_HABITACION_PK" PRIMARY KEY ("ID_STATUS_HABITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."STATUS_HABITACION" MODIFY ("ID_STATUS_HABITACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO" ADD CONSTRAINT "ORDEN_PEDIDO_PK" PRIMARY KEY ("ID_ORDEN_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO" MODIFY ("ID_ORDEN_PEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HABITACION
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."HABITACION" ADD CONSTRAINT "HABITACION_PK" PRIMARY KEY ("ID_HABITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."HABITACION" MODIFY ("ID_HABITACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_PRODUCTO" ADD CONSTRAINT "TIPO_PRODUCTO_PK" PRIMARY KEY ("ID_TIPO_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."TIPO_PRODUCTO" MODIFY ("ID_TIPO_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MONEDA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."MONEDA" ADD CONSTRAINT "MONEDA_PK" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."MONEDA" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUBRO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."RUBRO" ADD CONSTRAINT "RUBRO_PK" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."RUBRO" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_CAMBIO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO" ADD CONSTRAINT "TIPO_CAMBIO_PK" PRIMARY KEY ("ID_TIPO_CAMBIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO" MODIFY ("ID_TIPO_CAMBIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."PERSONA" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL_USUARIO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."ROL_USUARIO" ADD CONSTRAINT "ROL_USUARIO_PK" PRIMARY KEY ("ID_ROL_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAFOLIO"  ENABLE;
  ALTER TABLE "HOSTALCLARITA"."ROL_USUARIO" MODIFY ("ID_ROL_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HABITACION
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."HABITACION" ADD CONSTRAINT "HABITACION_STATUSHABIT_FK" FOREIGN KEY ("ID_STATUS_HABITACION")
	  REFERENCES "HOSTALCLARITA"."STATUS_HABITACION" ("ID_STATUS_HABITACION") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."HABITACION" ADD CONSTRAINT "HABITACION_TIPOHABIT_FK" FOREIGN KEY ("ID_TIPO_HABITACION")
	  REFERENCES "HOSTALCLARITA"."TIPO_HABITACION" ("ID_TIPO_HABITACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MINUTA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."MINUTA" ADD CONSTRAINT "MINUTA_DIASEMANA_FK" FOREIGN KEY ("ID_DIA_SEMANA")
	  REFERENCES "HOSTALCLARITA"."DIA_SEMANA" ("ID_DIA_SEMANA") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."MINUTA" ADD CONSTRAINT "MINUTA_PLATO_FK" FOREIGN KEY ("ID_PLATO")
	  REFERENCES "HOSTALCLARITA"."PLATO" ("ID_PLATO") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."MINUTA" ADD CONSTRAINT "MINUTA_SERVICIOCOMEDOR_FK" FOREIGN KEY ("ID_SERVICIO_COMEDOR")
	  REFERENCES "HOSTALCLARITA"."SERVICIO_COMEDOR" ("ID_SERVICIO_COMEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO" ADD CONSTRAINT "ORDENPEDIDO_PROVEEDOR_FK" FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "HOSTALCLARITA"."PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO" ADD CONSTRAINT "ORDENPEDIDO_USUARIO_FK" FOREIGN KEY ("ID_USUARIO_CREA_OP")
	  REFERENCES "HOSTALCLARITA"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_PEDIDO_DET
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO_DET" ADD CONSTRAINT "ORDENPEDIDODET_ORDENPEDIDO_FK" FOREIGN KEY ("ID_ORDEN_PEDIDO")
	  REFERENCES "HOSTALCLARITA"."ORDEN_PEDIDO" ("ID_ORDEN_PEDIDO") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."ORDEN_PEDIDO_DET" ADD CONSTRAINT "ORDENPEDIDODET_PRODUCTO_FK" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "HOSTALCLARITA"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PERSONA" ADD CONSTRAINT "PERSONA_TIPOPERSONA_FK" FOREIGN KEY ("ID_TIPO_PERSONA")
	  REFERENCES "HOSTALCLARITA"."TIPO_PERSONA" ("ID_TIPO_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PROVEEDOR_FK" FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "HOSTALCLARITA"."PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_TIPOPRODUCTO_FK" FOREIGN KEY ("ID_TIPO_PRODUCTO")
	  REFERENCES "HOSTALCLARITA"."TIPO_PRODUCTO" ("ID_TIPO_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PERSONA_FK" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "HOSTALCLARITA"."PERSONA" ("ID_PERSONA") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_RUBRO_FK" FOREIGN KEY ("ID_RUBRO")
	  REFERENCES "HOSTALCLARITA"."RUBRO" ("ID_RUBRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."RESERVA" ADD CONSTRAINT "RESERVA_USUARIO_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "HOSTALCLARITA"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVA_DETALLE
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."RESERVA_DETALLE" ADD CONSTRAINT "RESERVADET_HABITACION_FK" FOREIGN KEY ("ID_HABITACION")
	  REFERENCES "HOSTALCLARITA"."HABITACION" ("ID_HABITACION") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."RESERVA_DETALLE" ADD CONSTRAINT "RESERVADET_PERSONA_FK" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "HOSTALCLARITA"."PERSONA" ("ID_PERSONA") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."RESERVA_DETALLE" ADD CONSTRAINT "RESERVADET_RESERVA_FK" FOREIGN KEY ("ID_RESERVA")
	  REFERENCES "HOSTALCLARITA"."RESERVA" ("ID_RESERVA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPO_CAMBIO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO" ADD CONSTRAINT "TIPOCAMBIO_MONEDADESTINO_FK" FOREIGN KEY ("ID_MONEDA_DESTINO")
	  REFERENCES "HOSTALCLARITA"."MONEDA" ("ID_MONEDA") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO" ADD CONSTRAINT "TIPOCAMBIO_MONEDAORIGEN_FK" FOREIGN KEY ("ID_MONEDA_ORIGEN")
	  REFERENCES "HOSTALCLARITA"."MONEDA" ("ID_MONEDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPO_CAMBIO_VALOR
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."TIPO_CAMBIO_VALOR" ADD CONSTRAINT "TIPOCAMBIOVALOR_TIPOCAMBIO_FK" FOREIGN KEY ("ID_TIPO_CAMBIO")
	  REFERENCES "HOSTALCLARITA"."TIPO_CAMBIO" ("ID_TIPO_CAMBIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "HOSTALCLARITA"."USUARIO" ADD CONSTRAINT "USUARIO_PERSONA_FK" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "HOSTALCLARITA"."PERSONA" ("ID_PERSONA") ENABLE;
  ALTER TABLE "HOSTALCLARITA"."USUARIO" ADD CONSTRAINT "USUARIO_ROLUSUARIO_FK" FOREIGN KEY ("ID_ROL_USUARIO")
	  REFERENCES "HOSTALCLARITA"."ROL_USUARIO" ("ID_ROL_USUARIO") ENABLE;
