/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.reserva;

import bll.EmpresaBLL;
import bll.ReservaBLL;
import dal.EmpresaComboDAL;
import java.sql.ResultSet;
import gui.Principal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Carlos Poblete (a.k.a Kyosuke Kasuga)
 */
public class ListadoReservas extends javax.swing.JFrame {

    /**
     * Creates new form ListadoReservas
     */
    public ListadoReservas() throws SQLException {
        initComponents();
        EmpresaBLL emp = new EmpresaBLL();
        
        for (EmpresaComboDAL empcombo : emp.EmpresasConId()) {
            cmb_Empresa.addItem(empcombo);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Reservas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmb_Empresa = new javax.swing.JComboBox();
        btn_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Listado de Reservas por Empresa");

        tbl_Reservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Reserva", "Nombre Empresa", "RUT Empresa", "Fecha Check-In", "Fecha Check-Out", "Cantidad de Huespedes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Reservas);

        jLabel2.setText("Empresa:");

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Buscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        try {
            EmpresaComboDAL emp = (EmpresaComboDAL)cmb_Empresa.getSelectedItem();
            ReservaBLL reservaDAO = new ReservaBLL();
            ResultSet rs = reservaDAO.ReservasPorEmpresa(emp.getId_empresa());
            DefaultTableModel dtm = new DefaultTableModel();

            dtm.addColumn("Numero Reserva");
            dtm.addColumn("Nombre Empresa");
            dtm.addColumn("RUT Empresa");
            dtm.addColumn("Fecha Check-In");
            dtm.addColumn("Fecha Check-Out");
            dtm.addColumn("Cantidad de Huespedes");
            
            String reserva_datos[] = new String[6];
            
            int cant_reservas = 0;
            
            while (rs.next()) {
                reserva_datos[0] = Integer.toString(rs.getInt("ID_RESERVA"));
                reserva_datos[1] = rs.getString("NOMBRE");
                reserva_datos[2] = rs.getString("RUT");
                reserva_datos[3] = rs.getString("FECHA_CHECKIN").substring(0, 10);
                reserva_datos[4] = rs.getString("FECHA_CHECKOUT").substring(0, 10);
                reserva_datos[5] = rs.getString("CANT_HUESPEDES");
                
                dtm.addRow(reserva_datos);
                
                cant_reservas = cant_reservas + 1;
            }
            if (cant_reservas == 0) {
                JOptionPane.showMessageDialog(this, "Empresa no tiene resrvas asignadas en el Hostal");
                this.tbl_Reservas.setVisible(false);
                this.jScrollPane2.setVisible(false);
            } else {
                this.tbl_Reservas.setVisible(true);
                this.jScrollPane2.setVisible(true);
            }
            tbl_Reservas.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(ListadoReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JComboBox cmb_Empresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Reservas;
    // End of variables declaration//GEN-END:variables
}
