//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX__WS_WEBPG_SECTION_HISTORY
    {
        public decimal SECTION_ID { get; set; }
        public decimal WS_APP_ID { get; set; }
        public decimal WEBPAGE_ID { get; set; }
        public Nullable<decimal> OLD_DISPLAY_SEQUENCE { get; set; }
        public Nullable<decimal> NEW_DISPLAY_SEQUENCE { get; set; }
        public string OLD_TITLE { get; set; }
        public string NEW_TITLE { get; set; }
        public string OLD_CONTENT { get; set; }
        public string NEW_CONTENT { get; set; }
        public string APPLICATION_USER_ID { get; set; }
        public System.DateTime CHANGE_DATE { get; set; }
    }
}
