//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX__WS_HISTORY
    {
        public decimal ROW_ID { get; set; }
        public decimal WS_APP_ID { get; set; }
        public decimal DATA_GRID_ID { get; set; }
        public string COLUMN_NAME { get; set; }
        public string OLD_VALUE { get; set; }
        public string NEW_VALUE { get; set; }
        public string APPLICATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CHANGE_DATE { get; set; }
    }
}
