//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPPROD
    {
        public decimal ID { get; set; }
        public decimal PRODUCTOID { get; set; }
        public decimal CANTIDAD { get; set; }
        public string UPC { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
