//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRAS()
        {
            this.COMPPROD = new HashSet<COMPPROD>();
        }
    
        public decimal ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        public Nullable<System.DateTime> FECHARECEPCION { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ID1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPPROD> COMPPROD { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
