//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURACIONPROVEEDOR
    {
        public decimal FACTURACIONPROVEEDORID { get; set; }
        public System.DateTime FECHAPAGO { get; set; }
        public System.DateTime FECHARECEPCION { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_2 { get; set; }
        public decimal PROVEEDORID { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
