//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTFACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTFACTURAS()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal NRO_ORDEN_COMPRA { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public System.DateTime FECHARECEPCION { get; set; }
        public decimal ORDENCOMPRANUMERO_1 { get; set; }
        public System.DateTime FECHAPAGO { get; set; }
        public decimal FACTURAID { get; set; }
        public decimal ORDENCOMPRANUMERO { get; set; }
        public decimal PRODUCTOID { get; set; }
        public decimal HOSTALID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
