//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTAL
    {
        public decimal HOSTALID { get; set; }
        public string HOSTALNOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public decimal EMPRESAID { get; set; }
    }
}
