//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public decimal INVENTARIOID { get; set; }
        public string PRODUCTOINVENTARIO { get; set; }
        public System.DateTime FECHARECEPCION { get; set; }
        public System.DateTime FECHAVENCIMIENTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal RUTPROVEEDOR { get; set; }
        public decimal PRODUCTOID { get; set; }
        public string PRODUCTO_PRODUCTOID { get; set; }
    }
}
