//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APEX__WS_LINKS> APEX__WS_LINKS { get; set; }
        public virtual DbSet<APEX__WS_NOTES> APEX__WS_NOTES { get; set; }
        public virtual DbSet<APEX__WS_ROWS> APEX__WS_ROWS { get; set; }
        public virtual DbSet<APEX__WS_TAGS> APEX__WS_TAGS { get; set; }
        public virtual DbSet<APEX__WS_WEBPG_SECTIONS> APEX__WS_WEBPG_SECTIONS { get; set; }
        public virtual DbSet<APEX_WS_FILES> APEX_WS_FILES { get; set; }
        public virtual DbSet<APEX1> APEX1 { get; set; }
        public virtual DbSet<COMPPROD> COMPPROD { get; set; }
        public virtual DbSet<COMPRAS> COMPRAS { get; set; }
        public virtual DbSet<DEMO_CUSTOMERS> DEMO_CUSTOMERS { get; set; }
        public virtual DbSet<DEMO_ORDER_ITEMS> DEMO_ORDER_ITEMS { get; set; }
        public virtual DbSet<DEMO_ORDERS> DEMO_ORDERS { get; set; }
        public virtual DbSet<DEMO_PRODUCT_INFO> DEMO_PRODUCT_INFO { get; set; }
        public virtual DbSet<DEMO_USERS> DEMO_USERS { get; set; }
        public virtual DbSet<DEPT> DEPT { get; set; }
        public virtual DbSet<EMP> EMP { get; set; }
        public virtual DbSet<EMPLEADOHOSTERIA> EMPLEADOHOSTERIA { get; set; }
        public virtual DbSet<EMPRESACLIENTE> EMPRESACLIENTE { get; set; }
        public virtual DbSet<FACTURACIONPROVEEDOR> FACTURACIONPROVEEDOR { get; set; }
        public virtual DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual DbSet<HABITACION> HABITACION { get; set; }
        public virtual DbSet<HISTFACTURAS> HISTFACTURAS { get; set; }
        public virtual DbSet<HUESPED> HUESPED { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<MOVIMIENTOINVENTARIO> MOVIMIENTOINVENTARIO { get; set; }
        public virtual DbSet<NIVELUSUARIO> NIVELUSUARIO { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RELATION_17> RELATION_17 { get; set; }
        public virtual DbSet<RELATION_26> RELATION_26 { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<SERVCOMEDOR> SERVCOMEDOR { get; set; }
        public virtual DbSet<SERVICIOCOMEDOR> SERVICIOCOMEDOR { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<STOCKRESERVA> STOCKRESERVA { get; set; }
        public virtual DbSet<APEX__WS_HISTORY> APEX__WS_HISTORY { get; set; }
        public virtual DbSet<APEX__WS_WEBPG_SECTION_HISTORY> APEX__WS_WEBPG_SECTION_HISTORY { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<HOSTAL> HOSTAL { get; set; }
        public virtual DbSet<TIPO_HABITACION> TIPO_HABITACION { get; set; }
    }
}
