//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVELUSUARIO
    {
        public decimal NIVELUSUARIOID { get; set; }
        public Nullable<byte> ADMINISTRADOR { get; set; }
        public Nullable<byte> CLIENTE { get; set; }
        public Nullable<byte> EMPLEADO { get; set; }
        public Nullable<byte> PROVEEDOR { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal FUNCIONARIO_FUNCIONARIOID { get; set; }
    }
}
