//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.COMPPROD = new HashSet<COMPPROD>();
            this.STOCK1 = new HashSet<STOCK>();
            this.PROVEEDOR1 = new HashSet<PROVEEDOR>();
            this.STOCK2 = new HashSet<STOCK>();
        }
    
        public decimal PRODUCTOID { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal STOCK { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public decimal PROVEEDORID { get; set; }
        public decimal HOSTALID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPPROD> COMPPROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCK1 { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCK2 { get; set; }
    }
}
