//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATION_26
    {
        public decimal RESERVAID { get; set; }
        public decimal HUESPEDID { get; set; }
        public decimal ORDENCOMPRA { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
    
        public virtual HUESPED HUESPED { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
