//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKRESERVA
    {
        public decimal ID { get; set; }
        public decimal RESERVAID { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
