//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_HABITACION
    {
        public decimal TIPOHABITACIONID { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public decimal NUMEROHABITACION { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
    }
}
