//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX__WS_ROWS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APEX__WS_ROWS()
        {
            this.APEX__WS_LINKS = new HashSet<APEX__WS_LINKS>();
            this.APEX__WS_NOTES = new HashSet<APEX__WS_NOTES>();
            this.APEX_WS_FILES = new HashSet<APEX_WS_FILES>();
            this.APEX__WS_TAGS = new HashSet<APEX__WS_TAGS>();
        }
    
        public decimal ID { get; set; }
        public decimal WS_APP_ID { get; set; }
        public decimal DATA_GRID_ID { get; set; }
        public string UNIQUE_VALUE { get; set; }
        public string TAGS { get; set; }
        public Nullable<decimal> PARENT_ROW_ID { get; set; }
        public string OWNER { get; set; }
        public string GEOCODE { get; set; }
        public Nullable<decimal> LOAD_ORDER { get; set; }
        public Nullable<decimal> CHANGE_COUNT { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public string C001 { get; set; }
        public string C002 { get; set; }
        public string C003 { get; set; }
        public string C004 { get; set; }
        public string C005 { get; set; }
        public string C006 { get; set; }
        public string C007 { get; set; }
        public string C008 { get; set; }
        public string C009 { get; set; }
        public string C010 { get; set; }
        public string C011 { get; set; }
        public string C012 { get; set; }
        public string C013 { get; set; }
        public string C014 { get; set; }
        public string C015 { get; set; }
        public string C016 { get; set; }
        public string C017 { get; set; }
        public string C018 { get; set; }
        public string C019 { get; set; }
        public string C020 { get; set; }
        public string C021 { get; set; }
        public string C022 { get; set; }
        public string C023 { get; set; }
        public string C024 { get; set; }
        public string C025 { get; set; }
        public string C026 { get; set; }
        public string C027 { get; set; }
        public string C028 { get; set; }
        public string C029 { get; set; }
        public string C030 { get; set; }
        public string C031 { get; set; }
        public string C032 { get; set; }
        public string C033 { get; set; }
        public string C034 { get; set; }
        public string C035 { get; set; }
        public string C036 { get; set; }
        public string C037 { get; set; }
        public string C038 { get; set; }
        public string C039 { get; set; }
        public string C040 { get; set; }
        public string C041 { get; set; }
        public string C042 { get; set; }
        public string C043 { get; set; }
        public string C044 { get; set; }
        public string C045 { get; set; }
        public string C046 { get; set; }
        public string C047 { get; set; }
        public string C048 { get; set; }
        public string C049 { get; set; }
        public string C050 { get; set; }
        public Nullable<decimal> N001 { get; set; }
        public Nullable<decimal> N002 { get; set; }
        public Nullable<decimal> N003 { get; set; }
        public Nullable<decimal> N004 { get; set; }
        public Nullable<decimal> N005 { get; set; }
        public Nullable<decimal> N006 { get; set; }
        public Nullable<decimal> N007 { get; set; }
        public Nullable<decimal> N008 { get; set; }
        public Nullable<decimal> N009 { get; set; }
        public Nullable<decimal> N010 { get; set; }
        public Nullable<decimal> N011 { get; set; }
        public Nullable<decimal> N012 { get; set; }
        public Nullable<decimal> N013 { get; set; }
        public Nullable<decimal> N014 { get; set; }
        public Nullable<decimal> N015 { get; set; }
        public Nullable<decimal> N016 { get; set; }
        public Nullable<decimal> N017 { get; set; }
        public Nullable<decimal> N018 { get; set; }
        public Nullable<decimal> N019 { get; set; }
        public Nullable<decimal> N020 { get; set; }
        public Nullable<decimal> N021 { get; set; }
        public Nullable<decimal> N022 { get; set; }
        public Nullable<decimal> N023 { get; set; }
        public Nullable<decimal> N024 { get; set; }
        public Nullable<decimal> N025 { get; set; }
        public Nullable<decimal> N026 { get; set; }
        public Nullable<decimal> N027 { get; set; }
        public Nullable<decimal> N028 { get; set; }
        public Nullable<decimal> N029 { get; set; }
        public Nullable<decimal> N030 { get; set; }
        public Nullable<decimal> N031 { get; set; }
        public Nullable<decimal> N032 { get; set; }
        public Nullable<decimal> N033 { get; set; }
        public Nullable<decimal> N034 { get; set; }
        public Nullable<decimal> N035 { get; set; }
        public Nullable<decimal> N036 { get; set; }
        public Nullable<decimal> N037 { get; set; }
        public Nullable<decimal> N038 { get; set; }
        public Nullable<decimal> N039 { get; set; }
        public Nullable<decimal> N040 { get; set; }
        public Nullable<decimal> N041 { get; set; }
        public Nullable<decimal> N042 { get; set; }
        public Nullable<decimal> N043 { get; set; }
        public Nullable<decimal> N044 { get; set; }
        public Nullable<decimal> N045 { get; set; }
        public Nullable<decimal> N046 { get; set; }
        public Nullable<decimal> N047 { get; set; }
        public Nullable<decimal> N048 { get; set; }
        public Nullable<decimal> N049 { get; set; }
        public Nullable<decimal> N050 { get; set; }
        public Nullable<System.DateTime> D001 { get; set; }
        public Nullable<System.DateTime> D002 { get; set; }
        public Nullable<System.DateTime> D003 { get; set; }
        public Nullable<System.DateTime> D004 { get; set; }
        public Nullable<System.DateTime> D005 { get; set; }
        public Nullable<System.DateTime> D006 { get; set; }
        public Nullable<System.DateTime> D007 { get; set; }
        public Nullable<System.DateTime> D008 { get; set; }
        public Nullable<System.DateTime> D009 { get; set; }
        public Nullable<System.DateTime> D010 { get; set; }
        public Nullable<System.DateTime> D011 { get; set; }
        public Nullable<System.DateTime> D012 { get; set; }
        public Nullable<System.DateTime> D013 { get; set; }
        public Nullable<System.DateTime> D014 { get; set; }
        public Nullable<System.DateTime> D015 { get; set; }
        public Nullable<System.DateTime> D016 { get; set; }
        public Nullable<System.DateTime> D017 { get; set; }
        public Nullable<System.DateTime> D018 { get; set; }
        public Nullable<System.DateTime> D019 { get; set; }
        public Nullable<System.DateTime> D020 { get; set; }
        public Nullable<System.DateTime> D021 { get; set; }
        public Nullable<System.DateTime> D022 { get; set; }
        public Nullable<System.DateTime> D023 { get; set; }
        public Nullable<System.DateTime> D024 { get; set; }
        public Nullable<System.DateTime> D025 { get; set; }
        public Nullable<System.DateTime> D026 { get; set; }
        public Nullable<System.DateTime> D027 { get; set; }
        public Nullable<System.DateTime> D028 { get; set; }
        public Nullable<System.DateTime> D029 { get; set; }
        public Nullable<System.DateTime> D030 { get; set; }
        public Nullable<System.DateTime> D031 { get; set; }
        public Nullable<System.DateTime> D032 { get; set; }
        public Nullable<System.DateTime> D033 { get; set; }
        public Nullable<System.DateTime> D034 { get; set; }
        public Nullable<System.DateTime> D035 { get; set; }
        public Nullable<System.DateTime> D036 { get; set; }
        public Nullable<System.DateTime> D037 { get; set; }
        public Nullable<System.DateTime> D038 { get; set; }
        public Nullable<System.DateTime> D039 { get; set; }
        public Nullable<System.DateTime> D040 { get; set; }
        public Nullable<System.DateTime> D041 { get; set; }
        public Nullable<System.DateTime> D042 { get; set; }
        public Nullable<System.DateTime> D043 { get; set; }
        public Nullable<System.DateTime> D044 { get; set; }
        public Nullable<System.DateTime> D045 { get; set; }
        public Nullable<System.DateTime> D046 { get; set; }
        public Nullable<System.DateTime> D047 { get; set; }
        public Nullable<System.DateTime> D048 { get; set; }
        public Nullable<System.DateTime> D049 { get; set; }
        public Nullable<System.DateTime> D050 { get; set; }
        public string CLOB001 { get; set; }
        public string SEARCH_CLOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APEX__WS_LINKS> APEX__WS_LINKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APEX__WS_NOTES> APEX__WS_NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APEX_WS_FILES> APEX_WS_FILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APEX__WS_TAGS> APEX__WS_TAGS { get; set; }
    }
}
