//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO_PRODUCT_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMO_PRODUCT_INFO()
        {
            this.DEMO_ORDER_ITEMS = new HashSet<DEMO_ORDER_ITEMS>();
        }
    
        public decimal PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public string PRODUCT_AVAIL { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public byte[] PRODUCT_IMAGE { get; set; }
        public string MIMETYPE { get; set; }
        public string FILENAME { get; set; }
        public Nullable<System.DateTime> IMAGE_LAST_UPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMO_ORDER_ITEMS> DEMO_ORDER_ITEMS { get; set; }
    }
}
