//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOHOSTERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOHOSTERIA()
        {
            this.SERVICIOCOMEDOR = new HashSet<SERVICIOCOMEDOR>();
        }
    
        public decimal EMPLEADOHOSTERIAID { get; set; }
        public Nullable<decimal> CODIGO_TIPO_EMPLEADO { get; set; }
        public int RUTEMPLEADO { get; set; }
        public string NOMBREEMPLEADO { get; set; }
        public decimal TELEFONOEMPLEADO { get; set; }
        public string APELLIDOEMPLEADO { get; set; }
        public decimal HOSTALID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOCOMEDOR> SERVICIOCOMEDOR { get; set; }
    }
}
