//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACION()
        {
            this.TIPO_HABITACION = new HashSet<TIPO_HABITACION>();
            this.RESERVA2 = new HashSet<RESERVA>();
        }
    
        public decimal NUMHAB { get; set; }
        public decimal PRECIO { get; set; }
        public string DISPONIBLE { get; set; }
        public decimal RESERVA_NRO_RESERVA { get; set; }
        public decimal RESERVAID { get; set; }
        public decimal TIPOHABITACIONID { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_HABITACION> TIPO_HABITACION { get; set; }
        public virtual RESERVA RESERVA { get; set; }
        public virtual RESERVA RESERVA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA2 { get; set; }
    }
}
