//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATION_17
    {
        public decimal PROVEEDOR_PROVEEDORID { get; set; }
        public decimal EMPHOST_EMPHOSTID { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
