//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.HABITACION = new HashSet<HABITACION>();
            this.HABITACION1 = new HashSet<HABITACION>();
            this.RELATION_26 = new HashSet<RELATION_26>();
            this.STOCKRESERVA = new HashSet<STOCKRESERVA>();
            this.HABITACION2 = new HashSet<HABITACION>();
        }
    
        public decimal NRO_RESERVA { get; set; }
        public decimal NRO_HABITACION { get; set; }
        public string Check_in { get; set; }
        public string CHECK_OUT { get; set; }
        public decimal EMPRESACLIENTEID { get; set; }
        public decimal RESERVAID { get; set; }
        public Nullable<decimal> SERVCOMEDORID { get; set; }
        public decimal HOSTALID { get; set; }
        public decimal FACTURAID { get; set; }
    
        public virtual EMPRESACLIENTE EMPRESACLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABITACION> HABITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABITACION> HABITACION1 { get; set; }
        public virtual HISTFACTURAS HISTFACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATION_26> RELATION_26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKRESERVA> STOCKRESERVA { get; set; }
        public virtual SERVCOMEDOR SERVCOMEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABITACION> HABITACION2 { get; set; }
    }
}
