//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortafolio2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVCOMEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVCOMEDOR()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal SERVCOMEDORID { get; set; }
        public Nullable<decimal> EJECUTIVO { get; set; }
        public Nullable<decimal> ESPECIAL { get; set; }
        public Nullable<decimal> GENERAL { get; set; }
        public Nullable<decimal> BUFFET { get; set; }
        public decimal EMPLEADOHOSTERIAID { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
