/*
Script de creación de secuencias, para base de datos del proyecto Hostal Doña Clarita
Autor: Carlos Poblete Araya (a.k.a Kyosuke Kasuga)
Fecha: 16-05-2018
*/

CREATE SEQUENCE SEC_RESERVA INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_RESERVA_DETALLE INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_HABITACION INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_TIPO_HABITACION INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_STATUS_HABITACION INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_PERSONA INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_TIPO_PERSONA INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_USUARIO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_ROL_USUARIO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_PROVEEDOR INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_RUBRO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_PRODUCTO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_TIPO_PRODUCTO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_TIPO_CAMBIO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_MONEDA INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_TIPO_CAMBIO_VALOR INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_PLATO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_SERVICIO_COMEDOR INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_DIA_SEMANA INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_ORDEN_PEDIDO INCREMENT BY 1 START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE SEC_ORDEN_PEDIDO_DET INCREMENT BY 1 START WITH 1 NOCACHE ORDER;