/*
Poblamiento de datos para tabla DIA_SEMANA
Autor: Carlos Poblete Araya (a.k.a Kyosuke Kasuga)
Fecha: 19-05-2018
*/

INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('LUNES');
INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('MARTES');
INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('MIERCOLES');
INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('JUEVES');
INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('VIERNES');
INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('SABADO');
INSERT INTO DIA_SEMANA (DSC_DIA_SEMANA) VALUES ('DOMINGO');